// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5nL3KTIGTAFTYmaYi71s4tEbsuclH7Q',
    appId: '1:586250582515:web:96b8ae28e72e5df3fa3a86',
    messagingSenderId: '586250582515',
    projectId: 'geolpo-b5512',
    authDomain: 'geolpo-b5512.firebaseapp.com',
    storageBucket: 'geolpo-b5512.appspot.com',
    measurementId: 'G-PV4CGB3X2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2O0mLbEF51nUjBf_KQEC7UwY9TrQjQE',
    appId: '1:586250582515:android:beee6fbfa4f8589bfa3a86',
    messagingSenderId: '586250582515',
    projectId: 'geolpo-b5512',
    storageBucket: 'geolpo-b5512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEEJMvmlHbJAD5WV3wPl5-acm7O064CA',
    appId: '1:586250582515:ios:0394df21eb1148c2fa3a86',
    messagingSenderId: '586250582515',
    projectId: 'geolpo-b5512',
    storageBucket: 'geolpo-b5512.appspot.com',
    iosBundleId: 'com.geolpo.geolpo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEEJMvmlHbJAD5WV3wPl5-acm7O064CA',
    appId: '1:586250582515:ios:0394df21eb1148c2fa3a86',
    messagingSenderId: '586250582515',
    projectId: 'geolpo-b5512',
    storageBucket: 'geolpo-b5512.appspot.com',
    iosBundleId: 'com.geolpo.geolpo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY5nL3KTIGTAFTYmaYi71s4tEbsuclH7Q',
    appId: '1:586250582515:web:ac14126d7c8c2868fa3a86',
    messagingSenderId: '586250582515',
    projectId: 'geolpo-b5512',
    authDomain: 'geolpo-b5512.firebaseapp.com',
    storageBucket: 'geolpo-b5512.appspot.com',
    measurementId: 'G-XGXV6DJGHC',
  );

}